### ISSUE TITLE
require code

### ISSUE THREAD

**Issue by huangsusan** [Senyh/UCMT#1]
Hello：
I am very intrested in your work,and I am doing research on semi-supervised .If I publish a paper,I will referance your work.if your are convenience ,you could sent your code to my email 869075256@qq.com

**Comment by Senyh** [comment]
> Hello： I am very intrested in your work,and I am doing research on semi-supervised .If I publish a paper,I will referance your work.if your are convenience ,you could sent your code to my email [869075256@qq.com](mailto:869075256@qq.com)

Thank you for your interest. However, as the paper is currently under review, I'm not able to share the code at this time. The code will be made available in this repo upon publication of the paper.
