### ISSUE TITLE
恭喜作者获得IJCAI录用，我想问几个问题

### ISSUE THREAD

**Issue by 847001315** [Senyh/UCMT#3]
1. 论文的基线是什么模型
2. Table2中的息肉分割结果排行榜中，其他方法均是您自己复现的嘛？我看那些方法似乎不是息肉分割半监督的模型？

**Comment by 847001315** [comment]
在训练代码中， parser.add_argument('--labeled_percentage', type=int, default=0.05, help='the percentage of labeled data')，这里的type需要改成float，否则无法在命令行中输入，或者直接修改default也可。

**Comment by Senyh** [comment]
感谢您对我们工作的关注！
对于您提出问题的回复如下：
1 MT和CPS为所提方法的基准模型；
2 Table 2中，MT、CPS和CCT为我们复现的结果。AdvSemiSeg和ColAdv引用自ColAdv。

同时，感谢您的建议！对于image和label不匹配的问题，读取list后加上sorted应可以解决。

**Comment by 847001315** [comment]
> 感谢您对我们工作的关注！ 对于您提出问题的回复如下： 1 MT和CPS为所提方法的基准模型； 2 Table 2中，MT、CPS和CCT为我们复现的结果。AdvSemiSeg和ColAdv引用自ColAdv。
> 
> 同时，感谢您的建议！对于image和label不匹配的问题，读取list后加上sorted应可以解决。

好的，谢谢您的回复，目前正在精读你们的论文，如果有十分困惑又长期无法解决的问题，可能又要打扰你们了！

**Comment by 847001315** [comment]
作者您好，您的论文中跑了三个数据集，分别是ISIC2018、Colonoscopy 和 3D LA数据集，ISIC2018与Colonoscopy的数据集形式接近，通过修改部分配置就能跑通，那3D的心脏数据集是否需要额外的代码或者配置呢？文中提到的滑动窗口方法，我在源码中似乎没找到

**Comment by Senyh** [comment]
您好，3D部分的代码后续会和我们下一个工作一起开源。
3D和2D是类似的，您可以参考readme后面提到的repo。

**Comment by 847001315** [comment]
> 

好的，谢谢您的回复，我去相应的repo上去进行学习

**Comment by 847001315** [comment]
论文中给出的实验设置为epoch=50，batchsize=16，而代码中的默认设置epoch=25，batchsize=8。此处batchsize=8，分别是有标签的8和无标签的8，所以一共16，那么epoch数量是为什么会×2，是因为有两个学生模型？还是因为有标签训练算一个epoch，无标签训练又算另外一个epoch？此处是我的困惑，我使用epoch=25成功复现出您论文对应的结果！

**Comment by Senyh** [comment]
您好，对此问题，您参考原文实验设置的脚注就明白了。

**Comment by 847001315** [comment]
> 您好，对此问题，您参考原文实验设置的脚注就明白了。

非常抱歉！！ 是我没有仔细看论文！
![image](https://github.com/Senyh/UCMT/assets/49674990/9ef6d5fc-759a-49a2-bb85-4ff1adfba5d1)
谢谢您的及时回复~

**Comment by 847001315** [comment]
作者您好，我复现了您的代码后，发现在ISIC2018上基本上完美复现，在Kvasir和ClinicDB上都出现了性能下降1-2个点的情况，我预计应该是因为split_data的时候，是进行随机划分的，这里导致了数据出现了差异，请问是否方便发送一下你们的Kvasir和ClinicDB划分后的数据集，我的邮箱是：847001315@qq.com，由于我已经重新划分2-3次了，目前还是没有很好的结果，所以才来求助您的！ 万分感谢！！！

**Comment by Senyh** [comment]
您好，这个数据集划分请参考https://github.com/DengPingFan/PraNet

**Comment by 847001315** [comment]
> 您好，这个数据集划分请参考https://github.com/DengPingFan/PraNet

非常非常感谢，我还以为也是用split_data去实现的，我之前的数据集划分就是跟随PraNet的，真是令人欣喜。那请问，您是和Pra-net一样，将两个数据集的训练集合并去训练，还是单独分开训练？

**Comment by 847001315** [comment]
> 合并训练，分开测试

好的，感谢您的回答，我目前使用合并训练，分开测试，在Kvasir上可以达到与论文几乎一致的水准，而在ClinicDB取得的效果远低于论文水准，几乎少了3个点多，而且会出现15%的比例结果优于30%训练集的结果的情况，请问是否有什么训练细节需要注意的嘛？

**Comment by Senyh** [comment]
您可以尝试打乱并固定训练数据，比如打乱后保存为一个list，之后取15%或30%就按照该list取（即保证30%包含15%全部的数据），就不会出现15%优于30%的情况。
没有其他训练细节，导致结果存在差异的原因应该是随机选择有标签数据。

**Comment by 847001315** [comment]
> 您可以尝试打乱并固定训练数据，比如打乱后保存为一个list，之后取15%或30%就按照该list取（即保证30%包含15%全部的数据），就不会出现15%优于30%的情况。 没有其他训练细节，导致结果存在差异的原因应该是随机选择有标签数据。

好的，谢谢您的回答！

**Comment by 847001315** [comment]
作者您好，我想了解一下，文中所说的高置信度区域是否可以为模型预测的病灶位置，而低置信度区域为模型预测的背景区域？

**Comment by 847001315** [comment]
明白了，我看代码
```
uncertainty_map1 = -1.0 * torch.sum(uncertainty_map1 * torch.log(uncertainty_map1 + 1e-6), dim=1,
                                                    keepdim=True)
```
这段代码的本质含义是将模型对图片的预测概率值转变成模型对图片的置信度区间，这里是否隐含了，我们进行交换的patch部分，基本是模型预测出来的病灶部分？
我的理解是否出现了偏差？
