### ISSUE TITLE
train_3d

### ISSUE THREAD

**Issue by wenbobaba** [Senyh/UCMT#8]
很抱歉再次打扰您,
我发现train_3d.py中的第318行计算第二阶段loss_s时使用的label是第一阶段的label,而不是第二阶段的label_umix,这种做法和2d数据集中使用第二阶段的label2做法不一致,是专属于3d数据集的方法吗?
同样的还有322行计算loss_u使用的也是第一阶段的pred_u_pseudo

**Comment by Senyh** [comment]
您好！感谢提醒。这两处应该是当初整理代码时的疏忽，改成带umix后缀的即可。

**Comment by wenbobaba** [comment]
感谢您的回复
