### ISSUE TITLE
train_3D

### ISSUE THREAD

**Issue by Commondaisy** [Senyh/UCMT#9]
作者，你好，我在复现train_3d的代码时，不知为何结果比论文高出近4个点左右，考虑了各个参数，也没找到原因。除此之外代码中的第76行和cutmix是一样的吗，参数中is_mix用在了何处。

**Comment by Commondaisy** [comment]
作者，你好，我还有一点疑问希望可以得到你的解答。在第二阶段的训练中，1.标记数据及其标签为何也要进行umix操作呢，从代码中看标记数据并没有进行交叉伪监督，也没参与到生成不确定性估计图中。2.标记数据为什么也没有和教师模型输出计算一致性损失

**Comment by Senyh** [comment]
1）UMix也适用于有标注数据，可以看成一种数据增广操作；标注数据有真实标注，不需要交叉伪监督；不确定性图在第一阶段计算。
2）同理，标注数据有真实标签监督，不需要再计算一致性。

**Comment by Commondaisy** [comment]
感谢作者您的回复，我在上述问题中提到我在对3d代码进行复现时，结果达到92左右，至今未找出原因，也许是因为设备问题，我又在其他设备进行复现，依旧如此，所以我在考虑是否和数据集在验证时和测试时使用的是一样的有关，但是我发现使用LA的大多数论文里都和作者您的使用方式一样，请问您遇到过类似问题嘛，有什么好的建议吗

**Comment by Senyh** [comment]
可以用最后一个模型做测试。或者，再单独划分一个测试集。

**Comment by Commondaisy** [comment]
亲爱的作者，您好，我听了您的建议，使用了最后一个模型进行测试也单独划分了一个测试集，效果有降低，但并不明显。因为您的工作确实做的很好，所以我还是想要尝试尽可能复现，所以想请问您在划分数据集时一直就是按照test和train.list进行划分的吗，有采取随即划分这样的情况吗

**Comment by Commondaisy** [comment]
作者，冒昧打扰了，接上述问题，论文中提到用滑动窗口策略迭代裁剪斑块，获得最终的测试分割掩码，这个过程在代码中有体现吗

**Comment by Senyh** [comment]
您好，
1）按照list划分；
2）参考eval.py文件中的test_single_case函数。
